env:
    browser: true
    es2022: true
extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
    - plugin:react/recommended
    - plugin:react-hooks/recommended
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
    ecmaVersion: latest
    sourceType: module
plugins:
    - '@typescript-eslint'
    - react
    - react-hooks
rules:
    indent:
        - error
        - 4
    eqeqeq:
        - error
    semi:
        - error
        - never
    quotes:
        - error
        - single
